// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFo2w1fItLV217azfUEH34i14y1v_TcoU',
    appId: '1:74270439431:web:c359696fa9e266f5c212a2',
    messagingSenderId: '74270439431',
    projectId: 'todolist-793a0',
    authDomain: 'todolist-793a0.firebaseapp.com',
    storageBucket: 'todolist-793a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0CwOPBeR7Y2oIxD9jM0gEHH-Znsuj1_I',
    appId: '1:74270439431:ios:6cd3e685881c79dfc212a2',
    messagingSenderId: '74270439431',
    projectId: 'todolist-793a0',
    storageBucket: 'todolist-793a0.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0CwOPBeR7Y2oIxD9jM0gEHH-Znsuj1_I',
    appId: '1:74270439431:ios:6cd3e685881c79dfc212a2',
    messagingSenderId: '74270439431',
    projectId: 'todolist-793a0',
    storageBucket: 'todolist-793a0.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFo2w1fItLV217azfUEH34i14y1v_TcoU',
    appId: '1:74270439431:web:574c52a9c5153fb4c212a2',
    messagingSenderId: '74270439431',
    projectId: 'todolist-793a0',
    authDomain: 'todolist-793a0.firebaseapp.com',
    storageBucket: 'todolist-793a0.firebasestorage.app',
  );
}
